### ISSUE TITLE
why checksum = nil ?

### ISSUE THREAD

**Issue by sandersbasket** [SneakyOvis/onlyfans-dynamic-rules#1]
output:
```
{
  'app-token': '33d57ade8c02dbc5a333db99ff9ae26a',
  static_param: '7eTPrCi3dhXHQvXN7N42mC6Q05eNbooI',
  prefix: '6724',
  suffix: '63ce9b86',
  checksum_constant: 0,
  checksum_indexes: []
}
```

```
app.post('/create-headers/', async function (req, res) {
  const data = req.body;

  const html = await getPage('https://www.onlyfans.com');
  const code = await getCode(html, '3415.js');
  // parse ast
  const ast = parser.parse(code);

  const newCode = generator(ast).code
  // create rules
  const context = getSign(newCode, data.path);
  const rules = createRules(context.log, context.result.sign);

  res.status(200).json(createHeaders(data.path, rules, data.user_agent, data.user_id ));
});

```
![image](https://user-images.githubusercontent.com/101429671/214126357-b203a438-6147-4399-a09b-0ec006cf7347.png)

**Comment by SneakyOvis** [comment]
Sorry for late reply!

Well, there are two approaches.

#### Generate a sign from rules.

First, you shouldn't create rules on every post request, it's a waste of resources.
If you don't want to download already created rules from github, you should just create them yourself when your application starts, and then regenerate them only when you get an error from the OF api call.
Once you've parsed the original code, you'll need to work on it a little:

```js
const ast = parser.parse(code);
const math = getMath(ast);    // <-
const names = getNames(math); // <-
insertProxy(math, names);     // <-
parseOperations(math);        // <-
const newCode = generator(ast).code
```

After that, when you call the function that creates sign, you'll get a list of operations in the context.log and will be able to generate rules from that info.

#### Generate sign from the code.

If you want to parse code yourself, then you don't need rules and ast parsing anyway. Just generate the sign as you already do:

```js
// at start
const code = await getCode(html, '3415.js');
// in the post handler
const context = getSign(code, data.path);
context.result.sign // <- here's your sign
```

Or even better (not tested):

```js
// at start
function getSignFunction(code) {
    const context = runCode(code);
    return runFunction(context.self.webpackChunkof_vue[0][1][833415]);
}
const code = await getCode(html, '3415.js');
const genSign = getSignFunction(code);
// in the post handler
const result = genSign(data.path);
result.sign  // <- here's your sign
```

I hope this helps. :)
What are you trying to create, if it's not a secret?
