### ISSUE TITLE
Ruleset is different compared to DIGITALCRIMINALS

### ISSUE THREAD

**Issue by Shashank003** [SneakyOvis/onlyfans-dynamic-rules#2]
Why are the values of the static param, and checksum different compared to other similar repos.

**Comment by SneakyOvis** [comment]
The rules are automatically generated every 15 minutes, as you can see right here:
https://github.com/SneakyOvis/onlyfans-dynamic-rules/blob/main/.github/workflows/node.js.yml

When you look in the DIGITALCRIMINALS repository:
https://github.com/DIGITALCRIMINALS/dynamic-rules/blob/main/README.md
you'll see that:
```
I'm manually updating my fork. There's other providers that automatically update their rules and use the same format as my config.
```

If you want to see other repositories with as recent rules as mine, you can check this one:
https://github.com/deviint/onlyfans-dynamic-rules/blob/main/dynamicRules.json

**Comment by Shashank003** [comment]
Thanks for the help. For some reason, even though the values in the DIGITALCRIMINAL dynamic rules was outdated, it was still allowing me to make the calls. I'll instead make a call to your repo, and see if it works.

**Comment by SneakyOvis** [comment]
Yes, the rules do not expire immediately. If they did, all web clients would stop working and would have to be reloaded immediately. So the old version will work for a while, but I haven't investigated how long. I just like to always use current rules.
