### ISSUE TITLE
Error : please refresh the page

### ISSUE THREAD

**Issue by gollkn** [SneakyOvis/onlyfans-dynamic-rules#3]
Hello,  I'm making request as it's explained in readme ( also using new rules and copying all other info from browser correctly) but getting error : { error: { code: 401, message: 'Please refresh the page' } }

**Comment by SneakyOvis** [comment]
Make sure you have the current values of the relevant headers:
user-id, x-bc, cookie, user-agent.
Also, make sure that you're using the same IP address, so if you are using
proxy in your web browser, you need to implement it in your code.

If you can paste here minimal code here, I can check it with my own
headers. Or, if you want me to check your code with your headers,
catch me on Telegram. Don't paste your headers here :)

**Comment by SneakyOvis** [comment]
Issue resolved by private communication, the problem was wrong modifications to the original code.
