### ISSUE TITLE
try to generate x-bc

### ISSUE THREAD

**Issue by Gromov812** [SneakyOvis/onlyfans-dynamic-rules#4]
Hello @SneakyOvis ! 

I have to ask you for advice about x-bc generate. It always the same after log-in and it looks like it depends on constants, but in article you wrote that it variables as Date.now, 2 x Math.random and userAgent.

I'm trying to generate x-bc with code like: 
`sha1([(new Date).getTime(), 1e12*Math.random(), 1e12*Math.random(), window.navigator.userAgent].map(btoa).join('.'))`

so.. of course it always not the same with original x-bc sign. Can you give me advice what way should i do? Thanks!

**Comment by SneakyOvis** [comment]
Hey!

The x-bc value is generated once and used for a long time.
Unfortunately, I do not know the conditions that force the
generation of a new value - whether it is time period,
the number of logins, or the version of the web application.

**Comment by Gromov812** [comment]
> Hey!
> 
> The x-bc value is generated once and used for a long time. Unfortunately, I do not know the conditions that force the generation of a new value - whether it is time period, the number of logins, or the version of the web application.

Thanks a lot for your answer

**Comment by SneakyOvis** [comment]
Not a problem, wish you best with your project :)
If you need any help, you can catch me by an email.
