### ISSUE TITLE
Script Modification

### ISSUE THREAD

**Issue by nahdoud** [SneakyOvis/onlyfans-dynamic-rules#5]
Hello Sir Can You Modify This Script And Make It work For Me Please Update It 

public static (string, string) kof(string path)
{
    string static_param = "jd6jc4asoDCTZuqCM1SLkiCTy5oGFUhy";
    var format = "7096:{0}:{1:x}:63f36c1b";
    var checksum_indexes = new int[] { 21, 20, 6, 31, 18, 37, 31, 23, 17, 18, 32, 27, 6, 34, 35, 0, 6, 0, 0, 27, 36, 17, 36, 31, 27, 8, 9, 26, 20, 1, 32, 3 };
    var checksum_constants = new int[] { 73, -124, 91, -82, -126, -121, -145, 93, 112, -85, -133, -110, -77, 98, 78, -123, -99, -70, 90, -138, 107, -93, 96, -84, -98, -129, -98, 108, 128, 129, -115, -68 };
    var checksum_constant = -915;
    string time = ((int)DateTime.UtcNow.Subtract(new DateTime(1970, 1, 1)).TotalSeconds).ToString();
    string[] param = { static_param, time, path, "0" };
    string message = string.Join("\n", param);
    byte[] messageBytes = System.Text.Encoding.UTF8.GetBytes(message);
    using (System.Security.Cryptography.SHA1 sha1 = System.Security.Cryptography.SHA1.Create())
    {
        byte[] sha1Bytes = sha1.ComputeHash(messageBytes);
        string sha1Sign = BitConverter.ToString(sha1Bytes).Replace("-", "").ToLower();
        byte[] sha1SignBytes = System.Text.Encoding.ASCII.GetBytes(sha1Sign);
        int checksum = checksum_indexes.Sum(i => sha1SignBytes[i]) + checksum_constant;
        string formatString = string.Format(format, sha1Sign, Math.Abs(checksum));
        return (formatString, time);
    }
}

(string sign, string now) = kof("/api2/v2/users/login");

**Comment by SneakyOvis** [comment]
I don't have the C# environment at hand, but you can try updating the values using those:

https://github.com/DIGITALCRIMINALS/dynamic-rules/blob/main/onlyfans.json
