### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by blblbl303** [SneakyOvis/onlyfans-dynamic-rules#7]
Hello. I have not been able to get in touch with you. Can I ask you some questions on api? I am a beginner and can't understand how to make queries on onlyfans.

**Comment by SneakyOvis** [comment]
Sure, ask. You can contact me directly, the info is public, you just need to be able to read.
And there are two examples how to use api - js and python. If you have problem with that,
then I would say that you should learn to program first :)
