### ISSUE TITLE
THANK YOU !

### ISSUE THREAD

**Issue by Ghost6446** [SneakyOvis/onlyfans-dynamic-rules#8]
How long did it take you to reverse the original function and figure out what it does ?

**Comment by SneakyOvis** [comment]
Thanks :)
Don't remember how long, sorry. Less than a day for sure.
But the documentation... This was a real challenge - to get it all right and semi-understandable :)

**Comment by Ghost6446** [comment]
From where did you start learning babel ?

**Comment by SneakyOvis** [comment]
From Babel website :)
Or you can just search for "Babel tutorial".
If you have some programming experience, for example, you have created a simple compiler before, that would be helpful.
At the very least, you should understand concepts such as parser, token, AST, etc.

**Comment by Ghost6446** [comment]
Thank you for all.
