### ISSUE TITLE
Refresh page

### ISSUE THREAD

**Issue by Ghost6446** [SneakyOvis/onlyfans-dynamic-rules#9]
I dont know if was only my problem, i try implementing in a function like your but doest work. I try right generate sign from official api and work perfectly. I analyze the code but prefix are right maybe conversion from msg to ash1 is change.

**Comment by SneakyOvis** [comment]
Yes, the problem is your code, that's all I can be sure of :)

**Comment by Ghost6446** [comment]
[run_2.zip](https://github.com/SneakyOvis/onlyfans-dynamic-rules/files/13931829/run_2.zip)

Is just your code with little modification, but it doesnt work

**Comment by Ghost6446** [comment]
In chrome, debuggin 3415.js when return sign, it call object W with get headers, api ..., but when call 'getters.auth/authUserId', return null rappresent in the msg as '0', so changing msg to => '\n'.join(["lt9y0HLpodbUOvSp6qWmhPV7KQfxQ7PR", timestamp, path, "0"]) now it work. I dont know if it's only my problem.

**Comment by SneakyOvis** [comment]
Hey!

Here is a working, single file example. I've tested it right now, the server responds with 200.
Can you start from there and on every modification test if it's still working for you?

[test.zip](https://github.com/SneakyOvis/onlyfans-dynamic-rules/files/13938327/test.zip)

**Comment by Ghost6446** [comment]
Ok i will test, try my version with ccurl conveter instead of copy all cookie and headers as a string.

**Comment by Ghost6446** [comment]
> Hey!
> 
> Here is a working, single file example. I've tested it right now, the server responds with 200. Can you start from there and on every modification test if it's still working for you?
> 
> [test.zip](https://github.com/SneakyOvis/onlyfans-dynamic-rules/files/13938327/test.zip)

yeah it work fine

**Comment by Ghost6446** [comment]
One last question, why in funcion parse log after find operator 'get' that is 'mod', you add or sub to checksum constant only first operatorion, and not use other op if there is ?

**Comment by SneakyOvis** [comment]
Can you point me to the code you are referring to?

**Comment by Ghost6446** [comment]
if (entry[0] === 'get') {
            indexes.push(entry[2]);
            entry = log[i + 1];


This part

**Comment by SneakyOvis** [comment]
Why there's no "mod" operation here? Because I'm not intersted in modulo operations per se - they're here only as a part of obfuscation - to get indexes in specific range (sha hash length). I'm already logging final values of these indexes with "get" operation just a step before.

And the final result is explained here:
"Get a character value, add or subtract some number, remember the result. Get another character value, again add or subtract some number, add the result to the previous one. And so on. Now we need two things: all indexes that are accessed from sha hash, and sum of all added/substracted numbers."

Or, as an example:

let a=452;
let arr = 'string';
val = arr[a % arr.length]

I'm not interested much about "a % arr.length" operation, I would like to just know index value and it's always the same, it is not dependent on any input. In this case it comes down to:

let a=452;
let arr = 'string';
val = arr[2]

 Is that clear?

**Comment by Ghost6446** [comment]
Yes this is right , now that I write decode by my own, i can respond to my question, in the case of, 


Call -w 3
Add 23 
Sub 44

It is unecessary to use sub because we calcolate checksum with 

Chekcsum += (sha1[index] + operation)

So we have for example 32 index and 32 operation to add to the final checkum, and if we have more operation to add the checksum will be not at the end only for 3 char. 

Is that right ?

**Comment by SneakyOvis** [comment]
I'm not sure I understood what you mean :)

**Comment by Ghost6446** [comment]
I know, is a little bit complicate, i try upload a debug on what i have done with my second pc but it doesnt work. I will try today with main.

**Comment by Ghost6446** [comment]
> I'm not sure I understood what you mean :)

I try to explain what it done, !! or ;; is what i can't understand

[debug_2.txt](https://github.com/SneakyOvis/onlyfans-dynamic-rules/files/13964786/debug_2.txt)

**Comment by SneakyOvis** [comment]
Man, I really don't have much time to analyze your problem and this work was done a year ago, it's not like a yesterday :)
It all comes down do a simple calculating checkum by adding letter values of sha hash, selected by array of indexes. There's nothing left to dig for :)

`CALL (MOD);  18885 % 40  =  5               - num from math function % sha1.length() = 5        !!! _sub(_W[_n[t("i2Un", 424)](18885, _W[t("VpyM", 398)])`

I don't even know the question :)

`CALL (ADD);  -63 + -43  =  -106             - preve_const_checksum -= (prev sub) = -106         !!! WHAT THIS IS USE FOR ?????`

It's obfuscated code. There can be operations that are pointless or convoluted.

`  checksum: [                               !! len(checksum) = 32`

And?

`  checksum_index: [                         !! len(checksum_index) = 32         ;; if len(checksum) != from len(checksum_index) there is now way to calculate right checksum ?`

Let's say. So? :)

`!! PYTHON 
!! if len(checksum) !== len(checksum_index) it cant work`

Sure.
I don't know how I can help further. Are you trying to analyze Javascrip in Python?
If you like to make things harder, then have fun! :)

**Comment by Ghost6446** [comment]
Okay thank you very much anyway, sorry if I wasted your time. There is always a more difficult method that no one has ever done.

**Comment by SneakyOvis** [comment]
No no, that's ok. And you're right - there's always more fun in reverse engineering :)

**Comment by Ghost6446** [comment]
Yes, it is always funny and make you learn a lot of new knowledge reverse script in any language, i start with crackme and now ,site parameter and headers generator.

**Comment by Ghost6446** [comment]
> No no, that's ok. And you're right - there's always more fun in reverse engineering :)

I was analyzing this website to find the algorithm for creating the m3u8 file: https://goku.sx/watch-movie/watch-orion-and-the-dark-105823/1414609.
The main function for creating the m3u8 should be this one, the names always change, 0.25, 0.5 instead do not. The algorithm they use should be MD5.

hq = ()=>{
    var h = {};
    return h[hb] = [0.25, 0.5, 0.75, 0x1, 1.25, 1.5, 0x2],
    h[hw] = hr,
    h[hc] = h9,
    h[hD] = !0x1,       // m3u8
    h[hF] = {},
    h[hS] = hh,
    h;
}

The source where the m3u8 should be created is similar to this obtained after this request https://rabbitstream.net/ajax/embed-4/getSources?id=fRBzdRfZ2k8J", which returns U2FsIpCKh6GdGVkX1+QdpsTFZvSf+X0qrmkAsXlD1jE7ayVgDPivMqecHTSQFEqX6lJ1sJm4iQFT6NnkOYkmhFORps7QZwcO3viSXQQmyXTlDP7U2/kUqXd3wcreyd2uhGJwR67wMIIFX3rAZWqECJt+LfYWGZnB2kW16tuObsF6qzZe/0rGoLQMhKrQrrASF8qQhKRW5nXtyxv5fuzK8Qz5NkIX7OHciAjWw4u8UOWmWppa66fPajd9oiSpWAYocr3kQkSDMcvmG0I7jZlTmB57D/xQxVcilog4zLWt9pqZijpCx/6dEdOi+jOMlxHHixNZ6xqWCJoghV7By+T07Rk0MpUM/GIqr9/DMCqR08RMYQF3vIr3KaV1ltCu04ehhYf76O4lR+Jp7M7QKDH4QgE93Z4rYQKvEGGj5Laaql+SmMZbpL5NkWDJPKZ7OeVOgY98pXaXl7yZvYsajAcJkcKye7PHlGykLW/Q652udhE+TDgDtTOfJsS3nbq9FTpCKNnqTY8Kgy9OEMZLGDfML+lkL4wp6+tAzw2Obhefn

which is immediately converted to https://x.pollllop.com/_v11/9efa8a8d602507fedfca0c21b22ec8b86752cdf135925dd96bfda6839ab3b83166526926f674607dc71eb013e782cbd98ff1950a96289034d628afb501c60058dd6d0e48473e9383f01e41f71bf242c92b992bd34f3b36b1c65d4ffd47b30b0a18acaca79615df7ef7948e869362f29308424db82baf04017ba5e10c767268c521c6cc409a83ea7ae2b2a6072d36109e/playlist.m3u8

Without a request, the problem is that I can't find the function responsible for this. If you have time and willingness, could you give me a hand?

**Comment by SneakyOvis** [comment]
It's not within the scope of this repo :)

But, is this useful to you?
https://stackoverflow.com/questions/77200774/find-key-in-player-min-js-to-decode-string

Plus maybe some tools like this:
https://github.com/PerimeterX/restringer
https://github.com/j4k0xb/webcrack

**Comment by Ghost6446** [comment]
Yes i know is out of topics, but thank you for the help this will help a lot.

**Comment by Ghost6446** [comment]
const CryptoJS = require('crypto-js');

const iq = (i, F) => {
  try {
    var j = CryptoJS.AES.decrypt(i, F);
    return JSON.parse(j.toString(CryptoJS.enc.Utf8));
  } catch (u) {
    console.log(u.message);
  }
  return [];
};

// Example ciphertext and key
const ciphertext = "U2FsdGVkX1+a1BPr7kAgyOfE0cwKLeXoWHAlKGUph9rYwdPOTZNCwGaysA9TqgoRs41O9zimxFhZEy+F45lEuZsKge8+HhFaNH3ujfGjKOKFOUbnehty3JhJLJs+iqI/qbyd4sSc/GJc6P6DvEoAuzEZHHpBVx11RCx3SbiRt2QhePrF5R7bB+nZNCz/yDFDVR0G3oG85OZ4wFnw23fzZnoLEXw+KOo+Pmyky5iRcpx/QDbEWXqdaa/lsyLyDX36Zh32th6kmfOyGkvXi+YQrE5/f9AP18rJoSf8hilDL6zbeQWDzdP/fuZox5VzC5BXOJQ/+WoNaRiiFfAlqQPi2jMPucJ09knw7UC1NaPMgODTINDs8FeLVCHW2qnH6/+ow/apn36sNSo2E069x79MOwFns3RzOJPkXZJMvi75rCtlGdZ9fuIvTmCIK8dkjRpcUnjSJeREAOKK5payZLYniH2/0x796DYUZDy44U2gPuRjBudfbFSlb/cWEL7u1vUi";
const key = "JiC8vK7kDMWwBhh1DU8r4SV7f83uGk";

// Decrypt the ciphertext with the key
const decryptedData = iq(ciphertext, key);

console.log("Decrypted Data:", decryptedData);
thank you now i find the function, now is time to make a good code
